name: CI Docker Build and Tag

on:
    push:
        branches:
            - main
        tags:
            - 'v*.*.*'

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name : Leer la versión desde el package jason
              id: version
              run: |
                VERSION=$(node -p "require('./package.json').version")
                echo "Versión detectada: $VERSION"

            - name: Login to docker hub
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}
            - name: Build y tag de la imagen
              run: |
                docker build \
                    -t ${{secrets.DOCKER_USERNAME}}/node-scout:${{ steps.version.outputs.VERSION }}
                    -t ${{secrets.DOCKER_USERNAME}}/node-scout:latest
                    .
            - name: Push a Docker hub
              run: |
                docker push ${{secrets.DOCKER_USERNAME}}/node-scout:${{ steps.version.outputs.VERSION }}
                docker push ${{secrets.DOCKER_USERNAME}}/node-scout:latest