services:
  db:
    image: postgres:16-alpine
    container_name: pgdb
    restart: unless-stopped
    environment:
      POSTGRES_DB: iBaseDatos
      POSTGRES_USER: adonas
      POSTGRES_PASSWORD: Qwerty123.
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure              
volumes:
  pgdata:
